# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Eren Black
# Description of the Site
description: Motion Graphic Artist, Animator, Video Editor, and Temporizing Enthusiast.
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: Site, Portfolio, ErenBlackEdits, ErenBlack, Eren, Black, Editor, Graphic Design, Graphic Designer, Motion Design, Motion Designer
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://erenblack.com/assets/images/meta.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email:
facebook_username: 
twitter_username: ErenBlackEdits
instagram_username: 
linkedin_username: thedevslot
github_username:  
youtube_channel_id: erenblackedits
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
discord_username: Eren Black#6621
discord_server: https://discord.gg/RXz2sMs

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Eren Black
# URL for the Image of the Author
author-image: https://www.erenblack.com/assets/images/logo.png
# 60 Words About the Author
author-about: Please contact me via my socials, or via discord :)
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
